kind: ConfigMap
apiVersion: v1
metadata:
  name: notus
data:
  port: "3000"
  contract.address: "0xeb458b030d6be178e301910f7077955574bb7be4"
  ws.url: "wss://ropsten.infura.io/ws/v3/5e378f49a3994737940a897b2d95222b"
  ipfs.url: ""
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: notus
data:
  some.secret: "c3VwZXIgc2VjcmV0IHN0dWZmIHlvCg=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notus
  labels:
    app: notus
spec:
  selector:
    matchLabels:
      app: notus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: notus
    spec:
      containers:
      - name: notus
        image: ${IMAGE_NAME_COMMIT}
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: SOME_SECRET
          valueFrom:
            secretKeyRef:
              name: notus
              key: some.secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: notus
              key: port
        - name: CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: notus
              key: contract.address
        - name: WS_URL
          valueFrom:
            configMapKeyRef:
              name: notus
              key: ws.url
        - name: IPFS_URL
          valueFrom:
            configMapKeyRef:
              name: notus
              key: ipfs.url
---
kind: Service
apiVersion: v1
metadata:
  name: notus
spec:
  selector:
    app: notus
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notus
spec:
  tls:
    - secretName: notifyus-network-tls
  rules:
  - host: api.notifyus.network
    http:
      paths:
      - path: /
        backend:
          serviceName: notus
          servicePort: 80
